<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace my_workspace\Updater\Models\Operations;


class ReadOrderResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Successful operation
     * 
     * @var ?\my_workspace\Updater\Models\Operations\ReadOrder200ApplicationJSON $readOrder200ApplicationJSONObject
     */
	
    public ?ReadOrder200ApplicationJSON $readOrder200ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->readOrder200ApplicationJSONObject = null;
	}
}
