<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace my_workspace\Updater\Models\Operations;

use \my_workspace\Updater\Utils\SpeakeasyMetadata;
class ReadOrderRequest
{
    /**
     * ID of order to return
     * 
     * @var int $orderId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=orderId')]
    public int $orderId;
    
	public function __construct()
	{
		$this->orderId = 0;
	}
}
