<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace my_workspace\Updater\Models\Operations;


/**
 * ReadOrderResponseBody - Successful operation
 * 
 * @package my_workspace\Updater\Models\Operations
 * @access public
 */
class ReadOrderResponseBody
{
	#[\JMS\Serializer\Annotation\SerializedName('order')]
    #[\JMS\Serializer\Annotation\Type('my_workspace\Updater\Models\Shared\Order')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\my_workspace\Updater\Models\Shared\Order $order = null;
    
    /**
     * Where the most current state of the object came from.
     * 
     * @var ?string $origin
     */
	#[\JMS\Serializer\Annotation\SerializedName('origin')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $origin = null;
    
	public function __construct()
	{
		$this->order = null;
		$this->origin = null;
	}
}
