<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace my_workspace\Updater\Models\Operations;


class ReadDealResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Successful operation
     * 
     * @var ?\my_workspace\Updater\Models\Operations\ReadDeal200ApplicationJSON $readDeal200ApplicationJSONObject
     */
	
    public ?ReadDeal200ApplicationJSON $readDeal200ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->readDeal200ApplicationJSONObject = null;
	}
}
