<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace my_workspace\Updater\Models\Shared;


enum DealType: string
{
    case Percentage = 'percentage';
    case Amount = 'amount';
}
