<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace my_workspace\Updater\Models\Shared;


/** Represent the current state of the cart. Local cart states must be translated to these generic states in order to all e-commerces and management software and other kinds of software to understand the current state of the cart. */
enum State: string
{
    case PendingPayment = 'pending_payment';
    case PaymentReceived = 'payment_received';
    case OrderInvoice = 'order_invoice';
    case OrderShipped = 'order_shipped';
    case Complete = 'complete';
    case Canceled = 'canceled';
    case Refunded = 'refunded';
}
