<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace my_workspace\Updater;

/**
 * Updater - Updater: Updater is an API that allows every software being constantly updated with their respective e-commerce and vice-versa.
 * 
 * https://updater.com - Find out more about Updater
 * 
 * @package my_workspace\Updater
 * @access public
 * @see https://updater.com
 */
class Updater
{
	public const SERVERS = [
		'https://updater.com/api',
	];
  	
    /**
     * Obtain the last state of a deal (discount, promotion, etc) and perform new updates for a specific product.
     * 
     * @var Deal $$deal
     */
	public Deal $deal;
	
	public Order $order;
	
    /**
     * Obtain the last state of a product and perform new updates for a specific product.
     * 
     * @var Product $$product
     */
	public Product $product;
		
	private SDKConfiguration $sdkConfiguration;

	/**
	 * Returns a new instance of the SDK builder used to configure and create the SDK instance.
	 * 
	 * @return UpdaterBuilder
	 */
	public static function builder(): UpdaterBuilder
	{
		return new UpdaterBuilder();
	}

	/**
	 * @param SDKConfiguration $sdkConfiguration
	 */
	public function __construct(SDKConfiguration $sdkConfiguration)
	{
		$this->sdkConfiguration = $sdkConfiguration;
		
		$this->deal = new Deal($this->sdkConfiguration);
		
		$this->order = new Order($this->sdkConfiguration);
		
		$this->product = new Product($this->sdkConfiguration);
	}
}